server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/hope}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    uris: https://6c3c28c1c31c4680b19026beafcc41ce.ap-southeast-1.aws.found.io:443
    username: elastic
    password: kxuXzAQgrnazZ4loL99pKImK

jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_API_SECRET}