server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://root:xkSrecLhZWlfscyrLxJQVTtEtoHrTCJH@interchange.proxy.rlwy.net:24318/railway
    username: root
    password: xkSrecLhZWlfscyrLxJQVTtEtoHrTCJH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_API_SECRET}