server:
  port: ${PORT:8080}
  forward-headers-strategy: native

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3306/hope}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:https://6c3c28c1c31c4680b19026beafcc41ce.ap-southeast-1.aws.found.io:443}
    username: elastic
    password: ${ELASTICSEARCH_PASSWD}

jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_API_SECRET}



payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}

resend:
  api_key: ${RESEND_API_KEY:re_UMpdYfjz_M9xnHA7tsbmzMXff4ZSFZ3pk}