
jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_API_SECRET}
payments:
    url: ${SEPAY.BASE_URL}
    api_key: ${SEPAY_API_KEY}
    transaction:
      list: ${SEPAY_TRANSACTION_LIST}
      details: ${SEPAY_TRANSACTION_DETAIL}
      count: ${SEPAY_TRANSACTION_COUNT}