server:
  port: ${PORT:8080}
  forward-headers-strategy: native

spring:
  elasticsearch:
    enabled: ${ELASTICSEARCH_ENABLED:true}
    uris: http://152.42.199.139:9200
    username: elastic
    password: ${ELASTIC_PASSWORD:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:mysql://mysql:3306/hope
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
 
jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  secret-key: ${CLOUDINARY_API_SECRET}


client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}


  sepay:
    url: ${SEPAY.BASE_URL}
    api_key: ${SEPAY_API_KEY}
    transaction:
      list: ${SEPAY_TRANSACTION_LIST}
      details: ${SEPAY_TRANSACTION_DETAIL}
      count: ${SEPAY_TRANSACTION_COUNT}

resend:
  api_key: ${RESEND_API_KEY:re_UMpdYfjz_M9xnHA7tsbmzMXff4ZSFZ3pk}